### ISSUE TITLE
Spinner circle isn't centered

### ISSUE THREAD

**Issue by Corne2Plum3** [greenmg2003/osu-Mg-skin#17]
The spinner looks weird because the rotating part isn't centered. The center circle is moving freely and it's disturbing, in addition to be a bug.

https://user-images.githubusercontent.com/57914482/154847047-ed6e5442-cff1-4aad-a942-64618dd1ae8c.mp4

**Comment by greenmg2003** [comment]
I thought of this one, but I believe the scaling of the spinner circle is not right. Lemme try my best to fix it, and will tell ya soon about this problem! From now on, I may leave is as opened

**Comment by greenmg2003** [comment]
Thanks for telling me!

**Comment by greenmg2003** [comment]
> The center circle is moving freely and it's disturbing, in addition to be a bug.
Finally, I fixed! Will send ya proof later and I'll close this after showing proof!

**Comment by greenmg2003** [comment]
Better now, I guess?
https://streamable.com/b5z2bm

**Comment by Corne2Plum3** [comment]
> Better now, I guess? https://streamable.com/b5z2bm

It's better than before, but still not fixed: the center continues to move

**Comment by greenmg2003** [comment]
Ah shet. Hard to determine where the circle should be. Lemme take 10 - 20 more attempts

**Comment by Corne2Plum3** [comment]
Yes it's hard and it need a lot of attempts. Idk what program you use to make your elements but if your program supports layers, using a circle that perfectly works helps a lot:

![spinner-circle@2x](https://user-images.githubusercontent.com/57914482/154950109-7ad56151-adfd-4456-8ad1-cc5d6c18a1ff.png)

**Comment by greenmg2003** [comment]
> Yes it's hard and it need a lot of attempts. Idk what program you use to make your elements but if your program supports layers, using a circle that perfectly works helps a lot

Mainly I use Mediband paint to do all stuff. 

> ![spinner-circle@2x](https://user-images.githubusercontent.com/57914482/154950109-7ad56151-adfd-4456-8ad1-cc5d6c18a1ff.png)

And this spinner-circle, should I use it? Or continue using the old one? 🤔

**Comment by Corne2Plum3** [comment]
I mean, to draw a centered spinner circle without spending 30 minutes to center it, open with your program an existing spinner-circle which works. Then draw your circle on it, by using the same center of the circle you imported, and once you finished, remove the spinner-circle you used to center your hitcircle.

**Comment by greenmg2003** [comment]
> I mean, to draw a centered spinner circle without spending 30 minutes to center it, open with your program an existing spinner-circle which works. Then draw your circle on it, by using the same center of the circle you imported, and once you finished, remove the spinner-circle you used to center your hitcircle.

Ah yeah, I got what you mean! Thanks for the advice! ^^

**Comment by greenmg2003** [comment]
Ah yeah, I used one of the spinners for template and I rework again the spinner-circle thingy, and yep, it improved my performance! ^^
This time I skinned it in `@2x` first, then I downscaled it to make SD one, just in case I won't have to do this again when remaking the skin in HD :V 
Video proof: https://streamable.com/oqoljq
